# Generated by Django 4.1.6 on 2023-02-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default=23123, max_length=13, verbose_name='Номер'),
            preserve_default=False,
        ),
    ]
