# Generated by Django 4.1.6 on 2023-02-11 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_pic_products', verbose_name='Картинки')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('description_adds', models.TextField(blank=True, max_length=300, null=True)),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('Published', 'Опубликовано'), ('On_deleted', 'На удалении')], default='On_moderated', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание')),
                ('date_of_publication', models.DateTimeField(verbose_name='Дата публикации')),
                ('edited_at', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds', to=settings.AUTH_USER_MODEL, verbose_name='Автор объявления')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50, verbose_name='category_name')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_comment', models.TextField(max_length=2000, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создание комментария')),
                ('adds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adds', to='webapp.adds', verbose_name='Объявления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
            ],
            options={
                'permissions': [('view_not_moderated_review', 'Видеть не модерированые отзывы')],
            },
        ),
        migrations.AddField(
            model_name='adds',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='webapp.category', verbose_name='Категория'),
        ),
    ]
