# Generated by Django 4.1.6 on 2023-02-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_adds_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='date_of_publication',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
