# Generated by Django 4.1.6 on 2023-02-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_adds_date_of_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/user_adds_image', verbose_name='Картинки'),
        ),
    ]
