# Generated by Django 4.1.6 on 2023-02-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_adds_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='status',
            field=models.CharField(choices=[('On_moderated', 'На модерации'), ('Published', 'Опубликовано'), ('On_deleted', 'На удалении')], default='On_moderated', max_length=50, verbose_name='Статус'),
        ),
    ]
