# Generated by Django 4.1.6 on 2023-02-11 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_alter_adds_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adds',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='webapp.category', verbose_name='Категория'),
        ),
    ]
