# Generated by Django 4.1.6 on 2023-02-11 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_adds_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adds',
            name='date_of_publication',
        ),
    ]
