# Generated by Django 4.1.6 on 2023-02-11 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_adds_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='adds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.adds', verbose_name='Объявления'),
        ),
    ]
