# Generated by Django 4.1.6 on 2023-02-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_alter_adds_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adds',
            options={'permissions': [('view_not_moderated_adds', 'Видеть не модерированые объявления')]},
        ),
    ]
