# Generated by Django 4.1.6 on 2023-02-11 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_alter_adds_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={},
        ),
    ]
